name: Multi Docker GHCR with Trivy scan

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile1"
      - "Dockerfile2"
      - "Dockerfile3"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: Dockerfile1
            image: app1
          - file: Dockerfile2
            image: app2
          - file: Dockerfile3
            image: app3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect file changes
        id: changed
        run: |
          if git diff --name-only HEAD~1 | grep -q "${{ matrix.file }}"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GitHub Container Registry
        if: steps.changed.outputs.changed == 'true'
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Docker image
        if: steps.changed.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          docker build -f ${{ matrix.file }} -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Run Trivy scan
        if: steps.changed.outputs.changed == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          format: table
          output: trivy-${{ matrix.image }}.txt
          exit-code: 0
          vuln-type: os,library
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM,LOW

      - name: Upload Trivy reports
        if: steps.changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ matrix.image }}
          path: trivy-${{ matrix.image }}.txt


  


