name: Multi Docker Build & Scan
# Force GitHub to reload workflow 

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile1"
      - "Dockerfile2"
      - "Dockerfile3"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Check and build Dockerfile1
      - name: Build, Push & Scan Dockerfile1
        id: docker1
        run: |
          if git diff --name-only HEAD~1 | grep -q 'Dockerfile1'; then
            echo "Dockerfile1 changed, building..."
            IMAGE=ghcr.io/${{ vaishnavi0706 }}/app1:latest
            docker build -f Dockerfile1 -t $IMAGE .
            docker push $IMAGE
            docker run --rm aquasec/trivy image --no-progress -f table -o trivy-app1.txt $IMAGE
          else
            echo "Dockerfile1 not changed, skipping."
          fi

      # Check and build Dockerfile2
      - name: Build, Push & Scan Dockerfile2
        id: docker2
        run: |
          if git diff --name-only HEAD~1 | grep -q 'Dockerfile2'; then
            echo "Dockerfile2 changed, building..."
            IMAGE=ghcr.io/${{ vaishnavi0706  }}/app2:latest
            docker build -f Dockerfile2 -t $IMAGE .
            docker push $IMAGE
            docker run --rm aquasec/trivy image --no-progress -f table -o trivy-app2.txt $IMAGE
          else
            echo "Dockerfile2 not changed, skipping."
          fi

      # Check and build Dockerfile3
      - name: Build, Push & Scan Dockerfile3
        id: docker3
        run: |
          if git diff --name-only HEAD~1 | grep -q 'Dockerfile3'; then
            echo "Dockerfile3 changed, building..."
            IMAGE=ghcr.io/${{ vaishnavi0706  }}/app3:latest
            docker build -f Dockerfile3 -t $IMAGE .
            docker push $IMAGE
            docker run --rm aquasec/trivy image --no-progress -f table -o trivy-app3.txt $IMAGE
          else
            echo "Dockerfile3 not changed, skipping."
          fi

      # Upload all Trivy reports
      - name: Upload Trivy Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-app1.txt
            trivy-app2.txt
            trivy-app3.txt
        continue-on-error: true

