name: Multi Docker GHCR with Trivy

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile1"
      - "Dockerfile2"
      - "Dockerfile3"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: Dockerfile1
            image: app1
          - file: Dockerfile2
            image: app2
          - file: Dockerfile3
            image: app3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if file changed
        id: changed
        run: |
          if git diff --name-only HEAD~1 | grep -q "${{ matrix.file }}"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        if: steps.changed.outputs.changed == 'true'
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image
        if: steps.changed.outputs.changed == 'true'
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          docker build -f ${{ matrix.file }} -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Trivy scan
        if: steps.changed.outputs.changed == 'true'
        run: |
          trivy image --format table -o trivy-${{ matrix.image }}.txt $IMAGE

      - name: Upload report
        if: steps.changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ matrix.image }}
          path: trivy-${{ matrix.image }}.txt

